import { Button } from "@/components/ui/button";
import { FilesIcon, StarIcon } from "lucide-react";
import Link from "next/link";


/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="container mx-auto pt-12">
    <div className="flex gap-8">
    <div className="w-40 flex flex-col gap-4">
      <Link href="/dashboard/files">
        <Button variant={"link"} className="flex gap-2">
          <FilesIcon /> All Files
        </Button>
      </Link>
      <Link href="/dashboard/favorites">
        <Button variant={"link"} className="flex gap-2">
          <StarIcon /> Favorites
        </Button>
      </Link>
    </div>

    <div className="w-full">{children}</div>
    </div>
  </main>
  );
}
