import { Button } from "@/components/ui/button";
import { FilesIcon, StarIcon } from "lucide-react";
import Link from "next/link";
import SideNav from "./side-nav";


/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="container mx-auto pt-12">
    <div className="flex gap-8">
    <div className="w-40 flex flex-col gap-4">
      <SideNav />
    </div>

    <div className="w-full">{children}</div>
    </div>
  </main>
  );
}
